# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_position_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='active',
        ),
    ]
